bootstrap_peers: []
node_config_network:
  activation_account_name: tqbaker
  chain_name: TEZOS_GRANADANET_2021-05-21T15:00:00Z
  genesis:
    block: BLockGenesisGenesisGenesisGenesisGenesisd4299hBGVoU
    protocol: PtYuensgYBb3G3x1hLLbCmcav8ue8Kyd2khADcL5LsT5R1hcXex
    timestamp: "2021-05-21T15:00:00Z"
  user_activated_upgrades:
  - level: 4095
    replacement_protocol: PsGraNadatF72MEA6sTufJB2uVKtRXbDMbJo7SNzKjAfdx9bP5q
images:
  tezos: tezos/tezos:test-release_917437eb_20210521140907
is_invitation: false
nodes:
  baking:
    tezos-baking-node-0:
      bake_using_account: tqbaker
      config:
        shell:
          history_mode: archive
      is_bootstrap_node: true
  regular: null
rpc_auth: false
zerotier_config:
  zerotier_network: null
  zerotier_token: null
zerotier_in_use: false

full_snapshot_url: null
rolling_snapshot_url: null
accounts:
  ecadlabs:
    key: edpkvP1NXoo8vhYbPSvXdy466EHoYWBpf6zmjghB2p3DwJPjbB5nsf
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: '5000000000000'
  smartpy:
    key: edpktv8Advoagbpo5TiyyDnmC1Mqne6vJMaXQ2vvuzUfJnBfMKJmdC
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: '5000000000000'
  bruno:
    key: edpkuu3jmS3kbaLYTmyVaPHaxowC1KP8fDSrLoJhcvip1Cm2tK5QCd
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: '5000000000000'
  tezosil:
    key: edpkvQj8r3YigN6QFsDRaKQCoxDNhKK4whDUkFkw6Gom36d86uhEbv
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: '5000000000000'
  pirbo:
    key: edpkuGH2TWTQ5JrwzBLGRu5is1h7vcv5e5LN45VfqmXS5zaTUMpopH
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: '5000000000000'
  luke:
    key: p2pk66gP3wq6k9QgNwAgaGLeXc3YFfrxgYdC7cdYuJWAHYBw4hExVHW
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: '5000000000000'
  marco:
    key: edpkuh3WSwziyd6nXqDXeh48vZHp5ETxFd43EdkbzhmW98BvuLXK81
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: '5000000000000'
  tz1THUNA:
    # Romain's faucet
    key: edpkuh3WSwziyd6nXqDXeh48vZHp5ETxFd43EdkbzhmW98BvuLXK81
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "500000000000000"
  tzbtc_admin:
    # admin for the test token contract that stands in for tzBTC.
    # (put here to test liquidity baking)
    key: edpkuBknW28nW72KG6RoHtYW7p12T6GKc7nAbwYX5m8Wd9sDVC9yav
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "5000000000000000"
  tqbaker:
    bootstrap_balance: '5000000000000'
    is_bootstrap_baker_account: true
    type: secret
    # key injected by pulumi
  tqfree:
    bootstrap_balance: '5000000000000000'
    is_bootstrap_baker_account: false
    type: secret
    # key injected by pulumi


activation:
  protocol_hash: PsFLorenaUUuikDWvMDr6fGBRG8kt3e3D3fHoXK1j1BFRxeSH4i
  protocol_parameters:
    preserved_cycles: 3
    blocks_per_cycle: 2048
    blocks_per_commitment: 16
    blocks_per_roll_snapshot: 128
    blocks_per_voting_period: 10240
    time_between_blocks:
      - "30"
      - "20"
    endorsers_per_block: 32
    hard_gas_limit_per_operation: "1040000"
    hard_gas_limit_per_block: "10400000"
    proof_of_work_threshold: "70368744177663"
    tokens_per_roll: "8000000000"
    michelson_maximum_type_size: 1000
    seed_nonce_revelation_tip: "125000"
    origination_size: 257
    block_security_deposit: "512000000"
    endorsement_security_deposit: "64000000"
    baking_reward_per_endorsement:
      - "1250000"
      - "187500"
    endorsement_reward:
      - "1250000"
      - "833333"
    cost_per_byte: "250"
    hard_storage_limit_per_operation: "60000"
    quorum_min: 2000
    quorum_max: 7000
    min_proposal_quorum: 500
    initial_endorsers: 24
    delay_per_missing_endorsement: "4"
    test_chain_duration: "1966080"

protocols:
- command: 009-PsFLoren
- command: 010-PsGraNad
