node_config_network:
  activation_account_name: oxheadbaker
  chain_name: TEZOS_IDIAZABALNET_2021-11-06T15:00:00Z
  genesis:
    block: BMFCHw1mv3A71KpTuGD3MoFnkHk9wvTYjUzuR9QqiUumKGFG6pM
    protocol: Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P
    timestamp: "2021-11-06T15:00:00Z"

protocols:
  - command: alpha

activation:
  protocol_hash: ProtoALphaALphaALphaALphaALphaALphaALphaALphaDdp3zK
  protocol_parameters:
    preserved_cycles: 5
    blocks_per_cycle: 8192
    blocks_per_commitment: 64
    blocks_per_stake_snapshot: 512
    blocks_per_voting_period: 40960
    hard_gas_limit_per_operation: '1040000'
    hard_gas_limit_per_block: '5200000'
    proof_of_work_threshold: '-1'
    tokens_per_roll: '8000000000'
    seed_nonce_revelation_tip: '125000'
    baking_reward_fixed_portion: '10000000'
    baking_reward_bonus_per_slot: '4286'
    endorsing_reward_per_slot: '2857'
    hard_storage_limit_per_operation: '60000'
    origination_size: 257
    cost_per_byte: '1000'
    quorum_max: 7000
    quorum_min: 2000
    min_proposal_quorum: 500
    liquidity_baking_subsidy: '2500000'
    liquidity_baking_sunset_level: 525600
    liquidity_baking_escape_ema_threshold: 100000
    max_operations_time_to_live: 120
    round_durations:
      - "30"
      - "45"
    consensus_committee_size: 7000
    consensus_threshold: 4667
    minimal_participation_ratio:
      numerator: 2
      denominator: 3
    max_slashing_period: 2
    frozen_deposits_percentage: 10
    double_baking_punishment: "640000000"
    ratio_of_frozen_deposits_slashed_per_double_endorsement:
      numerator: 1
      denominator: 2
    delegate_selection: "random"

nodes:
  tezos-baking-node:
    instances:
      - bake_using_accounts:
          - oxheadbaker
        config:
          shell:
            history_mode: archive
          rpc:
            cors-headers: [ "content-type" ]
            cors-origin: [ "*" ]
        is_bootstrap_node: true
    runs:
      - octez_node
      - baker
    storage_size: 80Gi
  # Overwrite default values.yaml tezos-node
  tezos-node: null

bootstrap_peers: []
full_snapshot_url: null
rolling_snapshot_url: null

images:
  octez: tezos/tezos:master_ad57ec91_20211105162538
accounts:
  oxheadbaker:
    bootstrap_balance: '720000000000000'
    is_bootstrap_baker_account: true
    type: secret
    # key injected by pulumi
  oxheadfree:
    # an account with a lot of money in it
    # tz1foxFdz2ieSj8P9YxKYBTEqYbgFXXEeiQY
    key: edpkubSgCoMjB2a6vPWRNRHfGa6HUFfFyEUKoEQhWC8osnav8QzBdJ
    bootstrap_balance: "5000000000000000"
    is_bootstrap_baker_account: false
    type: public

  nomadic00:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpku3HFqm2abDUPG16fKXZHCCDCNLpBRvqbgQC1Ka4kFQHYi6S7Pf
    type: public
  nomadic01:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpkuQLedLGSNjfVXoT1PkJcERiQutZdMKWSzKHCSnEhpYjUXeE8LT
    type: public
  nomadic02:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpku5JHHNN4CV9XVZ2na4zwSjRaRABHBUsc9ujTGDfe98VDmrbt6N
    type: public
  nomadic03:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpkuf7dqkv617ZsQhavosmT5qXQxvQa3Ud2ZBQi6cKx5QEjkXm9TG
    type: public
  nomadic04:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpkto7unE5dMgguDMkVbAp6u6PRnEjzCCdULspJjdqJRzLHZUXN54
    type: public
  nomadic05:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpkum5U9Dcu8HswLaG4wDeih7HD3PJefRGLoMZSuStksbmYJeVaSe
    type: public
  nomadic06:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpkuyZsQw1ioHijuNSfPTJmou2HN672R3haywPotaP3LVRodbnkbD
    type: public
  nomadic07:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpkuGwsxhqqKN8xTTg66mFTgUuA3jU7AMH9ZwDETBg33QqKc7Xr1z
    type: public
  nomadic08:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpkupMPSkJKpSQxSpBD1jHdc53F1y79Ranvr1Twg7CY2i9RDqkQ3H
    type: public
  nomadic09:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpkukX7M9muTnqgxY3aBGkVXEXuhnxobVZKhT5zxbisbU49eD1crA
    type: public
  nomadic10:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpkteJqof5RFHc8JeTwTL6J9ZgMNxJT8MspjLUL7AuCAnytDxcjs5
    type: public
  nomadic11:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpkuEyuPpyUszCPTJeUmAVmpCaFyXah9Q1jschvyX9Z6haL5YBJ4Z
    type: public
  nomadic12:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpkuJUgU6iSL7xwiuFWkX8HRwTScHJTsGzPLH7g7bv9Y9WnepXBbA
    type: public
  nomadic13:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpktn5KiKPSrUnDkfP515rvL9okpxvzcpjev2xcCSCWJLHNkRA7Md
    type: public
  nomadic14:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpkvZVz1aWhgdB4QUTzwBcAhhBiiEVfHR3sWvXWJ9tUzyzopnbKdM
    type: public
  nomadic15:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpkvFwYwnkVMQcPC36usdkd7Vp8PMSam2asxtLg6iepvaXxerRKZE
    type: public
  nomadic16:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpkv9HowGporsaQNauuv8gJX1FqPTn36A4AAjfeA1bGEncZe5wg3D
    type: public
  nomadic17:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpkuH8anpAFPNa1NPsWeymqLgyWJ1bDSWSqnyP2dod6rqf8Mi6yw6
    type: public
  nomadic18:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpkvAKQvhm6PPaPh4AQp4SjxFEkjyGohoz9DMsCNUXC6GdHzzAo54
    type: public
  nomadic19:
    bootstrap_balance: '36000000000000'
    is_bootstrap_baker_account: true
    key: edpkvUf8SABxhiUXz9dhKvPqEWhanzYHpfzaKp4oBzR1ft8C8NtRCo
    type: public
