apiVersion: v1
kind: Service
metadata:
  labels:
    app: faucet
  name: faucet
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app: faucet
status:
  loadBalancer: {}
