accounts:
  oxheadbaker:
    # Oxhead Alpha's baker hosted in teztnets.xyz infra
    # tz1foXHgRzdYdaLgX6XhpZGxbBv42LZ6ubvE
    bootstrap_balance: "5000000000000"
    is_bootstrap_baker_account: true
    type: secret
    # key injected by pulumi
  oxheadfree:
    # an account with a lot of money in it
    # tz1foxFdz2ieSj8P9YxKYBTEqYbgFXXEeiQY
    key: edpkubSgCoMjB2a6vPWRNRHfGa6HUFfFyEUKoEQhWC8osnav8QzBdJ
    bootstrap_balance: "5000000000000000"
    is_bootstrap_baker_account: false
    type: public
  bakingbadfaucetbot:
    # an account with a lot of money in it
    # tz1KhnTgwoRRALBX6vRHRnydDGSBFsWtcJxc
    key: edpkuFRauFAdhipQu9s4xmfNJWmtLxPKpoaoG41gYGq5AgUA43Vxqx
    bootstrap_balance: "500000000000000"
    is_bootstrap_baker_account: false
    type: public
  coredump:
    # tz1Wn7JnLVf7PpTbaLQNzmNaF9z9UudWHGBR
    key: edpkttKzcNNCjanS2De2Nagnpg9Bk1SoNhxDC1hqCFvHHFjfeeBK1m
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "5000000000000"
  baketzforme:
    # tz1ctdqnKaPTLfHhUih2EeUSD4Rvdmvja6Gp
    key: edpkv5k4hzJRisqiN41ajLTwxvvAf5TEs4R9pyhXwrFQCFf85fJ87m
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "5000000000000"
  primate:
    # tz1fptewGRqdDvtKbTpZxUT9H9Susp2yVG3m
    key: edpkutGqCeJtRqWKiPDpxH6NRwGjG18oaYT8WETzZgXEtYm4o3j4jr
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "5000000000000"

node_config_network:
  activation_account_name: oxheadbaker
  chain_name: TEZOS_USDTZNET_2021-09-30T15:00:00Z
  genesis:
    block: BLockGenesisGenesisGenesisGenesisGenesis94ee4bjQDg5
    protocol: Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P
    timestamp: "2021-09-30T15:00:00Z"
  user_activated_upgrades:
    - level: 4095
      replacement_protocol: PsCUKj6wydGtDNGPRdxasZDs4esZcVD9tf44MMiVy46FkD9q1h9

bootstrap_peers: []

images:
  octez: registry.gitlab.com/tessellatedgeometry/stabletech:hangzhou_usdt

nodes:
  tezos-baking-node:
    instances:
      - bake_using_accounts:
          - oxheadbaker
        config:
          shell:
            history_mode: archive
          rpc:
            cors-headers: [ "content-type" ]
            cors-origin: [ "*" ]
        is_bootstrap_node: true
    runs:
      - baker
      - endorser
      - octez_node
    storage_size: 30Gi
  # Overwrite default values.yaml tezos-node
  tezos-node: null

activation:
  protocol_hash: PtGRANADsDU8R9daYKAgWnQYAJ64omN1o3KMGVCykShA97vQbvV
  protocol_parameters:
     preserved_cycles: 3
     blocks_per_cycle: 4096
     blocks_per_commitment: 32
     blocks_per_roll_snapshot: 256
     blocks_per_voting_period: 20480
     time_between_blocks:
       - "20"
       - "10"
     endorsers_per_block: 256
     hard_gas_limit_per_operation: "1040000"
     hard_gas_limit_per_block: "5200000"
     proof_of_work_threshold: "70368744177663"
     tokens_per_roll: "8000000000"
     seed_nonce_revelation_tip: "125000"
     origination_size: 257
     block_security_deposit: "640000000"
     endorsement_security_deposit: "2500000"
     baking_reward_per_endorsement:
       - "78125"
       - "11719"
     endorsement_reward:
       - "78125"
       - "52083"
     cost_per_byte: "250"
     hard_storage_limit_per_operation: "60000"
     quorum_min: 2000
     quorum_max: 7000
     min_proposal_quorum: 500
     initial_endorsers: 192
     delay_per_missing_endorsement: "2"
     liquidity_baking_escape_ema_threshold: 100000
     liquidity_baking_subsidy: '2500000'
     liquidity_baking_sunset_level: 525600
     minimal_block_delay: '15'
     michelson_maximum_type_size: 1000

protocols:
  - command: 010-PtGRANAD
  - command: 011-PsCUKj6w

full_snapshot_url: null
rolling_snapshot_url: null
