accounts:
  oxheadbaker:
    bootstrap_balance: "7500000000000"
    is_bootstrap_baker_account: true
    type: secret
    # key injected by pulumi
  oxheadfree:
    # an account with a lot of money in it
    # tz1foxFdz2ieSj8P9YxKYBTEqYbgFXXEeiQY
    key: edpkubSgCoMjB2a6vPWRNRHfGa6HUFfFyEUKoEQhWC8osnav8QzBdJ
    bootstrap_balance: "5000000000000000"
    is_bootstrap_baker_account: false
    type: public

node_config_network:
  activation_account_name: oxheadbaker
  chain_name: TEZOS_TENDERBAKENET_2021-10-20T15:00:00Z
  genesis:
    block: BMFCHw1mv3A71KpTuGD3MoFnkHk9wvTYjUzuR9QqiUumKGFG6pM
    protocol: Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P
    timestamp: "2021-10-20T15:00:00Z"

protocols:
  - command: alpha

activation:
  protocol_hash: ProtoALphaALphaALphaALphaALphaALphaALphaALphaDdp3zK
  protocol_parameters:
    preserved_cycles: 3
    blocks_per_cycle: 4096
    blocks_per_commitment: 32
    blocks_per_roll_snapshot: 256
    blocks_per_voting_period: 20480
    hard_gas_limit_per_operation: '800000'
    hard_gas_limit_per_block: '8000000'
    proof_of_work_threshold: '-1'
    tokens_per_roll: '8000000000'
    seed_nonce_revelation_tip: '125000'
    baking_reward_fixed_portion: '10000000'
    baking_reward_bonus_per_slot: '4286'
    endorsing_reward_per_slot: '2857'
    hard_storage_limit_per_operation: '60000'
    origination_size: 257
    cost_per_byte: '1000'
    quorum_max: 7000
    quorum_min: 2000
    min_proposal_quorum: 500
    liquidity_baking_subsidy: '2500000'
    liquidity_baking_sunset_level: 525600
    liquidity_baking_escape_ema_threshold: 100000
    round_durations:
      - "30"
      - "45"
    consensus_committee_size: 7000
    consensus_threshold: 4667
    minimal_participation_ratio:
      numerator: 2
      denominator: 3
    max_slashing_period: 2
    frozen_bonds_percentage: 10
    double_baking_punishment: "640000000"
    ratio_of_frozen_bonds_slashed_per_double_endorsement:
      numerator: 1
      denominator: 2
    delegate_selection: "random"

nodes:
  tezos-baking-node:
    instances:
      - bake_using_accounts:
          - oxheadbaker
        config:
          shell:
            history_mode: archive
          rpc:
            cors-headers: [ "content-type" ]
            cors-origin: [ "*" ]
        is_bootstrap_node: true
    runs:
      - octez_node
      - baker
    storage_size: 80Gi
  # Overwrite default values.yaml tezos-node
  tezos-node: null

bootstrap_peers: []
full_snapshot_url: null
rolling_snapshot_url: null

images:
  octez: registry.gitlab.com/nomadic-labs/tezos:amd64-tenderbake
