bootstrap_peers: []
node_config_network:
  activation_account_name: tqbaker
  chain_name: TEZOS_MONDAYNET_2021-04-26T00:00:00Z
  genesis:
    block: BMFCHw1mv3A71KpTuGD3MoFnkHk9wvTYjUzuR9QqiUumKGFG6pM
    protocol: PtYuensgYBb3G3x1hLLbCmcav8ue8Kyd2khADcL5LsT5R1hcXex
    timestamp: "2021-04-26T00:00:00Z"
images:
  tezos: tezos/tezos:master_786329ea_20210423192025
is_invitation: false
nodes:
  baking:
    tezos-baking-node-0:
      bake_using_account: tqbaker
      config:
        shell:
          history_mode: archive
      is_bootstrap_node: true
  regular: {}
rpc_auth: false
zerotier_config:
  zerotier_network: null
  zerotier_token: null
zerotier_in_use: false

full_snapshot_url: null
rolling_snapshot_url: null
accounts:
  ecadlabs:
    key: edpkvP1NXoo8vhYbPSvXdy466EHoYWBpf6zmjghB2p3DwJPjbB5nsf
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2500000000000"

      #two more accouts added by pulumi (not shown here):
      # * tq's baker
      # * tq's faucet

activation:
  protocol_hash: ProtoALphaALphaALphaALphaALphaALphaALphaALphaDdp3zK
  protocol_parameters:
    preserved_cycles: 3
    blocks_per_cycle: 2048
    blocks_per_commitment: 16
    blocks_per_roll_snapshot: 128
    blocks_per_voting_period: 1024
    time_between_blocks:
      - "30"
      - "20"
    endorsers_per_block: 32
    hard_gas_limit_per_operation: "1040000"
    hard_gas_limit_per_block: "10400000"
    proof_of_work_threshold: "70368744177663"
    tokens_per_roll: "8000000000"
    michelson_maximum_type_size: 1000
    seed_nonce_revelation_tip: "125000"
    origination_size: 257
    block_security_deposit: "512000000"
    endorsement_security_deposit: "64000000"
    baking_reward_per_endorsement:
      - "1250000"
      - "187500"
    endorsement_reward:
      - "1250000"
      - "833333"
    cost_per_byte: "250"
    hard_storage_limit_per_operation: "60000"
    test_chain_duration: "61440"
    quorum_min: 2000
    quorum_max: 7000
    min_proposal_quorum: 500
    initial_endorsers: 24
    delay_per_missing_endorsement: "4"
    minimal_block_delay: '1'
  should_include_commitments: true

protocol:
  command: alpha
