accounts:
  oxheadbaker:
    # tz1foXHgRzdYdaLgX6XhpZGxbBv42LZ6ubvE
    bootstrap_balance: "6700000000000"
    is_bootstrap_baker_account: true
    type: secret
    # key injected by pulumi
  tf_london:
    key: edpktzR9unKcG2XtsArVGNzQkrkUvbV3KAyWmX8XAsYFBLXwb1MicW
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "470000000000"
  tf_london2:
    key: edpktwQ93eJwcJUTkZYRKzDpMqNmY76av4xDmcYP6jTHKMHAvmwToi
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "470000000000"
  tf_london3:
    key: edpkue21EdnYUyHU9WHHMGEHA7E1HdTNy8pTZ4QQYodns7NUMFk1Fe
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "470000000000"
  tf_paris:
    key: edpktsx1JxD7cgTBXrgM7B8xUHVQ6cpFEk4rSUAEcuBPzi5wjjf3hZ
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "470000000000"
  tf_stockholm:
    key: edpkuiioYPwFA14hgSxnTFcS2enn2BqcMDkMrPVA3r7oZ86zGyphP3
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "470000000000"
  tf_frankfurt:
    key: edpkumfPbLdeawfWNWootvBMYGi83NDuPYvsaHgUoEL3BFRRLDGJQ3
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "470000000000"
  fifthelement:
    # tz1MeT8NACB8Q4uV9dPQ3YxXBmYgapbxQxQ5
    key: edpkujqmLUVGNbSNZV7CBMdtXAMGTTwJDQoXp2aRGrotys51rYvaRi
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "470000000000"
  jdsika:
    # tz1TGKSrZrBpND3PELJ43nVdyadoeiM1WMzb
    key: edpkutdFBe12UBzvgRKtAPbhQrpRA46oBSJCECeHswSLPzf6eAeqph
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "470000000000"
  ecadlabs:
    # tz1ck3EJwzFpbLVmXVuEn5Ptwzc6Aj14mHSH
    key: edpkvFUn1N79a7hGtVUF8AoQHf5q3A5g6xXtDcVTmna5wzHmgF1BfA
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "470000000000"
  german:
    #  tz1TGKSrZrBpND3PELJ43nVdyadoeiM1WMzb
    key: edpkvG8RpyhnPi3ugWWvavsKwR79rb7iMvedeFNxBdyCvenTDZeC9n
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "300000000000"
  oxheadfree:
    # an account with a lot of money in it
    # tz1foxFdz2ieSj8P9YxKYBTEqYbgFXXEeiQY
    key: edpkubSgCoMjB2a6vPWRNRHfGa6HUFfFyEUKoEQhWC8osnav8QzBdJ
    bootstrap_balance: "5000000000000000"
    is_bootstrap_baker_account: false
    type: public

node_config_network:
  activation_account_name: oxheadbaker
  genesis:
    block: BMFCHw1mv3A71KpTuGD3MoFnkHk9wvTYjUzuR9QqiUumKGFG6pM
    protocol: Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P
  user_activated_upgrades:
    - level: 1024
      replacement_protocol: ProtoALphaALphaALphaALphaALphaALphaALphaALphaDdp3zK

activation:
  protocol_hash: Psithaca2MLRFYargivpo7YvUr7wUDqyxrdhC5CQq78mRvimz6A
  protocol_parameters:
    preserved_cycles: 3
    blocks_per_cycle: 128
    blocks_per_commitment: 16
    blocks_per_stake_snapshot: 64
    blocks_per_voting_period: 128
    hard_gas_limit_per_operation: '1040000'
    hard_gas_limit_per_block: '5200000'
    proof_of_work_threshold: '-1'
    tokens_per_roll: '8000000000'
    seed_nonce_revelation_tip: '125000'
    baking_reward_fixed_portion: '10000000'
    baking_reward_bonus_per_slot: '4286'
    endorsing_reward_per_slot: '2857'
    hard_storage_limit_per_operation: '60000'
    origination_size: 257
    cost_per_byte: '250'
    quorum_max: 7000
    quorum_min: 2000
    min_proposal_quorum: 500
    liquidity_baking_subsidy: '2500000'
    liquidity_baking_sunset_level: 525600
    liquidity_baking_escape_ema_threshold: 100000
    max_operations_time_to_live: 120
    minimal_block_delay: "15"
    delay_increment_per_round: "15"
    consensus_committee_size: 7000
    consensus_threshold: 4667
    minimal_participation_ratio:
      numerator: 2
      denominator: 3
    max_slashing_period: 2
    frozen_deposits_percentage: 10
    double_baking_punishment: "640000000"
    ratio_of_frozen_deposits_slashed_per_double_endorsement:
      numerator: 1
      denominator: 2

nodes:
  tezos-baking-node:
    instances:
      - bake_using_accounts:
          - oxheadbaker
        config:
          shell:
            history_mode: archive
          rpc:
            cors-headers: [ "content-type" ]
            cors-origin: [ "*" ]
        is_bootstrap_node: true
    runs:
      - octez_node
      - baker
      - accuser
    readiness_probe: false
    storage_size: 15Gi
  # Overwrite default values.yaml rolling-node
  rolling-node: null

bootstrap_peers:
  - mondaynet.ecadinfra.com
    # tf
  - 18.132.213.248
  - 18.134.9.200
  - 18.134.13.112
    # end tf

full_snapshot_url: null
rolling_snapshot_url: null
rolling_tarball_url: null
archive_tarball_url: null

images: {}

protocols:
  - command: 012-Psithaca
  - command: alpha
